name: ShellCheck

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'URL del repositorio a escanear'
        required: true
        default: 'https://github.com/tu-usuario/tu-repositorio'
      branch:
        description: 'Nombre de la rama a escanear'
        required: true
        default: 'master'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.branch }}
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        args: '*.sh'
