name: ShellCheck

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Nombre de la rama a escanear'
        required: true
        default: 'master'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Run ShellCheck
      uses: azat-ai/shellcheck-action@v0.1.0
      with:
        args: '*.sh'
