name: ShellCheck

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Nombre del repositorio a escanear (formato: repo)'
        required: true
        default: 'Shell'
      branch:
        description: 'Nombre de la rama a escanear'
        required: true
        default: 'master'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: mvthivs23/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.TOKEN_ACTIONS }} # Usar el PAT configurado
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        args: '*.sh'