name: ShellCheck

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Nombre del repositorio a escanear (formato: repo)'
        required: true
        default: 'Shell'
      branch:
        description: 'Nombre de la rama a escanear'
        required: true
        default: 'master'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: mvthivs23/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.TOKEN_ACTIONS }} # Usar el PAT configurado
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        args: '*.sh'
        continue-on-error: true
    - name: Scan for sensitive data
      run: |
        echo "Scanning path: ${{ github.event.inputs.path }}"
        grep -r -i 'password\|user\|secret\|token' ${{ github.event.inputs.path }} || echo "No matches found."
        grep -r -iE '([\'\"].*password.*[\'\"]|[\'\"].*user.*[\'\"]|[\'\"].*secret.*[\'\"]|[\'\"].*token.*[\'\"])' ${{ github.event.inputs.path }} || echo "No matches found."