name: ShellCheck

on: 
 push:
  branches: ["main"]


jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: AzatAI/shellcheck@v0.1.0
      with:
        args: '*.sh'
