name: ShellCheck

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Nombre del repositorio a escanear (formato: repo)'
        required: true
        default: 'Shell'
      branch:
        description: 'Nombre de la rama a escanear'
        required: true
        default: 'master'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: mvthivs23/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.TOKEN_ACTIONS }} # Usar el PAT configurado
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        args: '${{ github.event.inputs.path }}/*.sh'
      continue-on-error: true

  sensitive-data:
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: mvthivs23/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.TOKEN_ACTIONS }}
    - name: Scan for sensitive data
      run: |
        echo "Escaneando datos sensibles en la shell..."

        # Define the pattern to search for
        PATTERN="PASS|PWD|PASSWORD|PSWD"

        # Perform the search and count matches
        MATCHES=$(grep -r -iE "$PATTERN" *.sh || true)
        
        if [ -z "$MATCHES" ]; then
          echo "-------------------------------------"
          echo "No se encontraron datos sensibles."
          echo "-------------------------------------"

        else
         echo "-------------------------------------"
         echo "-------------------------------------"
          echo "Se encontraron datos sensibles, favor revisar:"
          echo "$MATCHES"
          echo "-------------------------------------"
          echo "-------------------------------------"
          exit 1  # Fail the job if sensitive data is found
        fi