name: ShellCheck

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Nombre del repositorio a escanear (formato: repo)'
        required: true
        default: 'Shell'
      branch:
        description: 'Nombre de la rama a escanear'
        required: true
        default: 'master'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: mvthivs23/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.TOKEN_ACTIONS }} # Usar el PAT configurado
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
        args: '${{ github.event.inputs.path }}/*.sh'
      continue-on-error: true

  sensitive-data:
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: mvthivs23/${{ github.event.inputs.repo }}
        ref: ${{ github.event.inputs.branch }}
        token: ${{ secrets.TOKEN_ACTIONS }}
    - name: Scan for sensitive data
      run: |
        echo "Scanning for sensitive data in shell scripts..."

        # Define the pattern to search for
        PATTERN="PASS|PWD|PASSWORD|PSWD"

        # Create an HTML report
        REPORT_FILE="sensitive_data_report.html"
        echo "<html><body><h1>Sensitive Data Scan Report</h1>" > $REPORT_FILE
        echo "<h2>Search Pattern: $PATTERN</h2>" >> $REPORT_FILE

        # Perform the search and save results to the report
        grep -r -iE "$PATTERN" *.sh | sed 's/^/<p>/;s/$/<\/p>/' >> $REPORT_FILE

        echo "</body></html>" >> $REPORT_FILE
        
        # Check if report contains any matches
        if [ -s $REPORT_FILE ]; then
          echo "Sensitive data found. Report generated: $REPORT_FILE"
        else
          echo "No sensitive data found." >> $REPORT_FILE
        fi

    - name: Upload sensitive data report
      uses: actions/upload-artifact@v3
      with:
        name: sensitive-data-report
        path: sensitive_data_report.html